### ISSUE TITLE
Status of the plugin

### ISSUE THREAD

**Issue by sunjam** [ravensiris/opnsense-dyndns-porkbun#1]
Hi, checking on current status of this plugin in terms of compatibility with OpnSense.  Thanks for making it available!

**Comment by ravensiris** [comment]
Hi, I'm not sure what state I left this repo in. 
Pretty sure I gave up and used a python script + cron instead and the current repo doesn't do anything except add a panel to the admin panel.
I'm no longer in need for a opnsense plugin for this, thus I'll be archiving this and I'll pin this issue.
